# INTRODUÇÃO AO NUMBY E PANDAS

In [3]:
from array import array #array nativo

In [4]:
a = array('i', [1,2,3,4])

In [5]:
a

array('i', [1, 2, 3, 4])

In [1]:
import numpy as np

In [6]:
arr = np.array([18,23,33,44])

In [7]:
arr

array([18, 23, 33, 44])

In [8]:
arr * 2

array([36, 46, 66, 88])

In [ ]:
np.array((18,24,75,70))

In [10]:
matriz = np.array([[1.0,2],[3,4],[5,6]])
matriz

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [13]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
matriz.dtype

dtype('float64')

In [12]:
matriz.shape

(3, 2)

In [1]:
import numpy as np


In [3]:
arr = np.random.randint(0, 100, size = 10)

In [6]:
print(arr)
print(arr.dtype)

[45 49 87 87 67 79 91 95 17 62]
int32


In [7]:
import pandas as pd

In [8]:
mat = np.random.rand(5,5)

print(f"valor minimo:{np.min(mat)}")
print(f"valor maximo:{np.max(mat)}")
print(f"valor de media:{np.average(mat)}")

valor minimo:0.027713486830101997
valor maximo:0.9647679263457482
valor de media:0.5270032004104528


In [9]:
arr = np.random.rand(10)

arr_int = (arr * 10).astype(int)

print(arr)
print(arr_int)

[0.33327014 0.95957693 0.5571533  0.36185885 0.72689156 0.78111436
 0.79032984 0.90899548 0.65107599 0.02175881]
[3 9 5 3 7 7 7 9 6 0]


In [10]:
mat = np.random.randint(0,10, (3,3))

mat[1,:] = -1

print(mat)

[[ 1  3  8]
 [-1 -1 -1]
 [ 2  3  8]]


5. Crie um DataFrame com as seguintes informações:
 - Coluna "fruta": "Banana", "Maça", "Pera"
 - Coluna "preco": 7.90, 10.20, 11.80
 - Coluna "quantidade": 12, 3, 4
 

In [13]:

import pandas as pd

data ={"Fruta":["Banana","Maça", "Pera"],
       "Preço": [7.90,10.20,11.80],
       "Quantidade":[12,3,4]}

df = pd.DataFrame(data)

df

Fruta  Preço  Quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4

RECAPTULANDO AULA   -------------NUMPY----------


In [15]:
import numpy as np

arr = np.array([1,2,3,4]) # com lista


In [16]:
arr * 2

array([2, 4, 6, 8])

In [17]:
np.array((1,2,3,4)) # com tupla

array([1, 2, 3, 4])

In [19]:
# matriz

matriz = np.array([[1.2,3],[4,5]]) # os elementos das linhas tem que ter a mesma quantidade de valor

matriz

array([[1.2, 3. ],
       [4. , 5. ]])

In [24]:
matriz.shape

(2, 2)

In [22]:
#tensor

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,6]]]) # conjunto de matrizes

tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 6]]])

In [23]:
tensor.shape

(2, 2, 2)

In [25]:
# função one

ones = np.ones((3,3))

ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#função full

full = np.full((3,2), 'Junior')

full

array([['Junior', 'Junior'],
       ['Junior', 'Junior'],
       ['Junior', 'Junior']], dtype='<U6')

In [27]:
#função zeros

zeros = np.zeros((3,3))

zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# diagonal

np.diag(matriz)

array([1.2, 5. ])

In [30]:
# random.rand -cria valors de 0 a 1

np.random.rand(3,2)


array([[0.96418723, 0.77245912],
       [0.98226177, 0.82939141],
       [0.45281491, 0.10614172]])

In [31]:
# random.randint -cria valores de inteiros - devendo ser o intervalo especificados

np.random.randint(0,10, size=(3,2))

array([[1, 8],
       [1, 8],
       [9, 6]])

In [62]:
#Indexação

matriz = np.array([[1,2,3],[4,5,6]])
print(matriz[1, 2:3])

[6]


In [68]:

# Operações Logicas

print('sum: ', matriz.sum())
print('max: ', matriz.max())
print('min: ', matriz.min())
print('media: ', matriz.mean())
print('std: ', matriz.std())
print('var: ', matriz.var())

sum:  21
max:  6
min:  1
media:  3.5
std:  1.707825127659933
var:  2.9166666666666665


In [69]:
# Operação exponencial

np.exp(matriz)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

RECAPTULANDO AULA ------PANDAS------

In [74]:
### PANDAS --- SERIE

import pandas as pd

arr = np.array(range(20))

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
pd.Series(arr)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int32

In [80]:
nomes = np.array(['junior','carina','deleandro','vitor','gabriela'])

nomes

array(['junior', 'carina', 'deleandro', 'vitor', 'gabriela'], dtype='<U9')

In [81]:
pd.Series(nomes)

0       junior
1       carina
2    deleandro
3        vitor
4     gabriela
dtype: object

In [84]:
nomes = pd.Series(np.array(['junior','carina','deleandro','vitor','gabriela']), index=['a','b','c','d','e'])
nomes

a       junior
b       carina
c    deleandro
d        vitor
e     gabriela
dtype: object

In [ ]:
# PANDAS - DATAFRAME            

In [88]:
import numpy as np
import pandas as pd

nomes = np.array([['junior','gabi','carina'],['deleandro','vitor','pedro']])

In [89]:
df =pd.DataFrame(nomes) # criando dataframe atraves de array
df

0      1       2
0     junior   gabi  carina
1  deleandro  vitor   pedro

In [92]:
df = pd.DataFrame(nomes, columns=['nome1', 'nome2','nome3'], index=['a','b'])    #renomeando colunas
df

nome1  nome2   nome3
a     junior   gabi  carina
b  deleandro  vitor   pedro

In [101]:
####DATAFRAME POR DIRETORIO

nome_idade = {'Nome':['junior','gabi','carina','deleandro','vitor','pedro'], 'Idade':[41,16,33,31,32,71]}

df = pd.DataFrame(nome_idade, index=['a','b','c','d','e','f'])

df

Nome  Idade
a     junior     41
b       gabi     16
c     carina     33
d  deleandro     31
e      vitor     32
f      pedro     71

-----------EXERCICIOS------

In [122]:
#exercicio 1


arr = np.random.randint(0,100, size=(3,4))
arr


array([[80, 90, 66, 31],
       [ 7, 38, 16, 45],
       [94, 11,  1, 58]])

In [7]:
#exercicio 2
import numpy as np

matriz = np.random.rand(5,5)
print(f'Valor Máximo', matriz.max())
print(f'Valor Mínimo', matriz.min())
print(f'Valor Média', matriz.mean())


Valor Máximo 0.9482660457126795
Valor Mínimo 1.6782379197333164e-05
Valor Média 0.5213195894181402


In [28]:
#exercicio 3
import numpy as np

arr_1 = np.random.rand(10)

arr_2 = (arr_1 * 10).astype(int)

arr_1
arr_2

array([3, 8, 6, 1, 3, 7, 0, 1, 2, 4])

In [54]:
mat = np.random.randint(0, 10, (3, 3))

mat[1:2,] = -1
mat


array([[ 8,  5,  6],
       [-1, -1, -1],
       [ 5,  2,  3]])

In [56]:
import pandas as pd

data = {"fruta": ["Banana", "Maça", "Pera"],
        "preco": [7.90, 10.20, 11.80],
        "quantidade": [12, 3, 4]}

df = pd.DataFrame(data)
df

fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4