# INTRODUÇÃO AO NUMBY E PANDAS

In [3]:
from array import array #array nativo

In [4]:
a = array('i', [1,2,3,4])

In [5]:
a

array('i', [1, 2, 3, 4])

In [1]:
import numpy as np

In [6]:
arr = np.array([18,23,33,44])

In [7]:
arr

array([18, 23, 33, 44])

In [8]:
arr * 2

array([36, 46, 66, 88])

In [ ]:
np.array((18,24,75,70))

In [10]:
matriz = np.array([[1.0,2],[3,4],[5,6]])
matriz

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [13]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
matriz.dtype

dtype('float64')

In [12]:
matriz.shape

(3, 2)

In [1]:
import numpy as np


In [3]:
arr = np.random.randint(0, 100, size = 10)

In [6]:
print(arr)
print(arr.dtype)

[45 49 87 87 67 79 91 95 17 62]
int32


In [7]:
import pandas as pd

In [8]:
mat = np.random.rand(5,5)

print(f"valor minimo:{np.min(mat)}")
print(f"valor maximo:{np.max(mat)}")
print(f"valor de media:{np.average(mat)}")

valor minimo:0.027713486830101997
valor maximo:0.9647679263457482
valor de media:0.5270032004104528


In [9]:
arr = np.random.rand(10)

arr_int = (arr * 10).astype(int)

print(arr)
print(arr_int)

[0.33327014 0.95957693 0.5571533  0.36185885 0.72689156 0.78111436
 0.79032984 0.90899548 0.65107599 0.02175881]
[3 9 5 3 7 7 7 9 6 0]


In [10]:
mat = np.random.randint(0,10, (3,3))

mat[1,:] = -1

print(mat)

[[ 1  3  8]
 [-1 -1 -1]
 [ 2  3  8]]


5. Crie um DataFrame com as seguintes informações:
 - Coluna "fruta": "Banana", "Maça", "Pera"
 - Coluna "preco": 7.90, 10.20, 11.80
 - Coluna "quantidade": 12, 3, 4
 

In [13]:

import pandas as pd

data ={"Fruta":["Banana","Maça", "Pera"],
       "Preço": [7.90,10.20,11.80],
       "Quantidade":[12,3,4]}

df = pd.DataFrame(data)

df

Fruta  Preço  Quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4